### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by awinogradov** [awinogradov/react-bl#13]

**Comment by nik-kor** [comment]
what's the difference between popup and modal?

**Comment by awinogradov** [comment]
Styles and usage cases. Popup is technical block – platform for other block wich users can interact.

**Comment by tadatuta** [comment]
well, `popup` has target to position near and there can be a lot of popups on a page. and `modal` can only be just one as it blocks everything else on a page (adds additional fullscreen overlay layer)

**Comment by nik-kor** [comment]
work in progress https://github.com/awinogradov/react-bl/tree/feature/popup-component

**Comment by nik-kor** [comment]
https://github.com/awinogradov/react-bl/pull/33

**Comment by nik-kor** [comment]
continue in https://github.com/awinogradov/react-bl/issues/36 , https://github.com/awinogradov/react-bl/issues/37, https://github.com/awinogradov/react-bl/issues/38 https://github.com/awinogradov/react-bl/issues/39
