### ISSUE TITLE
onClick, onHover and etc is broken

### ISSUE THREAD

**Issue by awinogradov** [awinogradov/react-bl#25]
wrond `this` in all methods

**Comment by nik-kor** [comment]
do you mean, bind(this)

BTW this is cool https://github.com/andreypopp/autobind-decorator

**Comment by Guria** [comment]
@nik-kor it requires to enable `babel-plugin-transform-decorators-legacy`

**Comment by awinogradov** [comment]
fixed https://github.com/awinogradov/react-bl/commit/41934afd7611326a38a5215b21069c25cf448de4
