### ISSUE TITLE
choose package name

### ISSUE THREAD

**Issue by Guria** [awinogradov/react-bl#5]
[`react-components`](https://npmjs.com/package/react-components) is busy and we are not a Kik to grab it.
We should choose appropriate name for package.

**Comment by awinogradov** [comment]
I'm ready for variants;)

**Comment by vitkarpov** [comment]
> we are not a Kik to grab it

we can try and get pissed off another package author :)

**Comment by vitkarpov** [comment]
`react-islands-components` is free and it's a library of web components which implements yandex islands design and built on top of react. Everything converges.

**Comment by awinogradov** [comment]
It's not yandex library) Islands design only in examles folder;) many people want use it without styles.

**Comment by Guria** [comment]
* `react-primitives` its busy, but could ask author since it's only placeholder atm. https://github.com/lelandrichardson/react-primitives
* `react-controls`

**Comment by Guria** [comment]
* `@bem/react`
* `@bem/react-components`

**Comment by vitkarpov** [comment]
> It's not yandex library

I thought that it implement yandex islands design, sorry. So there's an ability to use islands skin, but it's not included by default?

**Comment by awinogradov** [comment]
Design is an option. See [examples](https://github.com/awinogradov/react-components/blob/master/examples/webpack.config.js#L63-L64) folder. Connection is easy.

**Comment by tadatuta** [comment]
react-blocks

**Comment by Guria** [comment]
@tadatuta great, but busy :(

**Comment by vitkarpov** [comment]
react-bl

**Comment by awinogradov** [comment]
`ui-components` is free

**Comment by awinogradov** [comment]
I think `react-bl` is very good ;)

**Comment by vitkarpov** [comment]
Yep, and it's free (not least of its pros :)

**Comment by awinogradov** [comment]
now is `react-bl`! Thanks @vitkarpov
